package airport

var indonesiaCities = map[string]string{
	"CGK": "Jakarta",
	"HLP": "Jakarta",
	"BDO": "Bandung",
	"SRG": "Semarang",
	"JOG": "Yogyakarta",
	"SOC": "Solo",
	"SUB": "Surabaya",
	"MLG": "Malang",
	"DPS": "Denpasar",
	"LOP": "Lombok",
	"BMU": "Bima",
	"SWQ": "Sumbawa Besar",
	"TMC": "Tambolaka",
	"WGP": "Waingapu",
	"MOF": "Maumere",
	"ENE": "Ende",
	"LBJ": "Labuan Bajo",
	"RTG": "Ruteng",
	"ARD": "Alor",
	"KOE": "Kupang",
	"BTJ": "Banda Aceh",
	"SBG": "Sabang",
	"KNO": "Medan",
	"MES": "Medan",
	"SIW": "Sibisa",
	"PDG": "Padang",
	"PKU": "Pekanbaru",
	"DUM": "Dumai",
	"BTH": "Batam",
	"TNJ": "Tanjung Pinang",
	"PLM": "Palembang",
	"TKG": "Bandar Lampung",
	"BKS": "Bengkulu",
	"DJB": "Jambi",
	"PNK": "Pontianak",
	"KTG": "Ketapang",
	"BDJ": "Banjarmasin",
	"BPN": "Balikpapan",
	"AAP": "Samarinda",
	"SRI": "Samarinda",
	"TRK": "Tarakan",
	"PGK": "Pangkal Pinang",
	"SNX": "Sabang",
	"UPG": "Makassar",
	"MDC": "Manado",
	"PLW": "Palu",
	"GTO": "Gorontalo",
	"KDI": "Kendari",
	"MJU": "Mamuju",
	"NAH": "Tahuna",
	"AMQ": "Ambon",
	"TTE": "Ternate",
	"GLX": "Galela",
	"DJJ": "Jayapura",
	"SOQ": "Sorong",
	"MKQ": "Merauke",
	"TIM": "Timika",
	"BIK": "Biak",
	"MKW": "Manokwari",
	"FKQ": "Fakfak",
	"WNI": "Wangi-Wangi",
}

// City returns the city name for a given airport code. Returns an empty string if the code is not found.
func City(code string) string {
	return indonesiaCities[code]
}
